// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Phase3Section5._7.Models
{
    public partial class Student
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Address { get; set; }
        [Required]
        [StringLength(75)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [StringLength(5)]
        [Unicode(false)]
        public string Class { get; set; }
    }
}